//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBinding {
    
    
    public partial class Cars {
        
        /// <summary>
        /// Producer control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList Producer;
        
        /// <summary>
        /// Models control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList Models;
        
        /// <summary>
        /// Extras control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBoxList Extras;

        protected global::System.Web.UI.WebControls.RadioButtonList Engine;

        protected global::System.Web.UI.WebControls.Panel CarsOptions;

        protected global::System.Web.UI.WebControls.Panel ResultContainer;

        protected global::System.Web.UI.WebControls.Literal SelectedProducer;

        protected global::System.Web.UI.WebControls.Literal SelectedModel;

        protected global::System.Web.UI.WebControls.Literal SelectedEngine;

        protected global::System.Web.UI.WebControls.BulletedList SelectedExtras;
    }
}
